version: '3.4'

services:
  md.backend.api.englishmovies:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6001:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  md.backend.api.indianmovies:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6002:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  md.backend.transmission:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6005:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
